#### I. Import Library

In [8]:
# Import Library
import pandas as pd
import numpy as np
from scipy import stats

# split data into train and test
from sklearn.model_selection import train_test_split

# feature scaling & encoding
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

# imputer
from sklearn.impute import SimpleImputer

# pipeline
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

# preprocessing
from sklearn.preprocessing import RobustScaler,PolynomialFeatures, StandardScaler

# Modeling
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.ensemble import GradientBoostingRegressor ,RandomForestRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

from sklearn.model_selection import cross_val_score, GridSearchCV

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

### II. Loading Data

In [9]:
df = pd.read_csv('D:\DataScience\github\ProjectMagang\Case1_BatuBara\Dataset\Mapping Variation.csv')
pd.set_option('display.max_columns', None)

In [10]:
df

,DATE,CV(AR),PRODUCT,TON\nSTOCKPILE,TON\nKROM,TPSHICV,TPS100,TPS200,TPSHICA,TPS300,TPS400,TPSA,TPS500,TPS600,TPSLOCV,TPSLOCTS,TPSLOCA,PBHICV,PB600,PB700,PBA,PBTS,PBLOCTS,PBLOCA,TSC12,TSC13,TSC33,TSC22,TSC23,TSCLOCV,TSCA,TSN100,TSN200,TSN300,TSNLOCV,WSHICV,WS100,WS200,WS300,BCSLSA,BCNLSA,BCSCM,BCNSCM,RAINFALL53,RAINHOUR54,RAINFALL55,RAINHOUR56,RAINFALL59,RAINHOUR60,RAINFALL61,RAINHOUR62,RAINFALL63,RAINHOUR64,SURVEYOR,WS_TON,CH_LITER
0,2-Jan-21,4872,E4900,0,0,0,0,0,1385,542,0,0,0,0,0,0,0,0,140,282,443,0,0,0,0,2550,0,1906,431,0,0,852,0,0,0,0,0,0,0,0,0,0,0,0.13,0.27,0.25,0.58,0.5,0.67,0.0,0.27,0.0,0.00,Geoservice,NaN,NaN
1,2-Jan-21,4018,WB,2282,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1225,0,2175,0,0,4618,0,0.13,0.27,0.25,0.58,0.5,0.67,0.0,0.27,0.0,0.00,Geoservice,NaN,NaN
2,2-Jan-21,4064,WB,5003,200,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3152,0,0,0,0,0,1851,0,0.13,0.27,0.25,0.58,0.5,0.67,0.0,0.27,0.0,0.00,Sucofindo,NaN,NaN
3,2-Jan-21,4896,E4900,2149,0,411,0,0,3190,1502,0,0,0,0,0,287,0,842,0,0,0,280,0,0,0,1297,0,139,1847,0,0,0,988,0,0,0,0,0,0,0,0,0,0,0.13,0.27,0.25,0.58,0.5,0.67,0.0,0.27,0.0,0.00,Sucofindo,95,262
4,2-Jan-21,4849,E4900,3798,0,410,0,0,2799,1260,0,0,0,0,0,0,0,415,0,0,0,1479,0,0,0,2533,0,0,2342,0,0,0,1864,0,0,0,0,0,0,0,0,0,0,0.13,0.27,0.25,0.58,0.5,0.67,0.0,0.27,0.0,0.00,Sucofindo,135,307
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6182,31-Jul-22,4856,E5000,0,0,556,0,0,1650,0,0,0,0,0,0,0,0,1940,0,0,0,0,0,0,2071,0,0,0,0,0,3750,1314,1847,0,0,0,0,0,0,0,0,0,0,0.80,4.13,1.65,7.29,0.4,6.92,2.0,7.33,3.0,6.83,Sucofindo,131,567
6183,31-Jul-22,4955,E5000,8855,0,403,0,0,3024,0,0,0,0,0,0,0,0,2335,0,0,0,0,0,0,134,0,0,0,0,0,1116,293,440,0,0,0,0,0,0,0,0,0,0,0.80,4.13,1.65,7.29,0.4,6.92,2.0,7.33,3.0,6.83,Sucofindo,85,373
6184,31-Jul-22,4685,E4700,0,600,687,0,0,847,1125,0,0,0,0,0,0,0,1101,0,0,0,0,0,0,1081,0,0,0,0,0,3763,865,827,0,0,0,0,0,987,0,0,0,0,0.80,4.13,1.65,7.29,0.4,6.92,2.0,7.33,3.0,6.83,Sucofindo,63,281
6185,31-Jul-22,5006,E5000,5589,1600,1098,0,0,860,597,0,0,0,0,0,0,0,3263,0,0,0,0,0,0,819,0,0,0,0,0,1946,1128,0,0,0,0,0,0,0,0,0,0,0,0.80,4.13,1.65,7.29,0.4,6.92,2.0,7.33,3.0,6.83,Sucofindo,117,508
6186,31-Jul-22,4926,E4900,988,0,406,0,0,2478,0,0,811,0,0,0,0,0,140,2988,0,0,0,0,0,1535,0,0,0,0,0,4308,1409,1436,0,0,0,0,0,0,0,0,0,0,0.80,4.13,1.65,7.29,0.4,6.92,2.0,7.33,3.0,6.83,Sucofindo,154,666

In [11]:
df.describe()

,CV(AR),TON\nSTOCKPILE,TON\nKROM,TPSHICV,TPS100,TPS200,TPSHICA,TPS300,TPS400,TPSA,TPS500,TPS600,TPSLOCV,TPSLOCTS,TPSLOCA,PBHICV,PB600,PB700,PBA,PBTS,PBLOCTS,PBLOCA,TSC12,TSC13,TSC33,TSC22,TSC23,TSCLOCV,TSCA,TSN100,TSN200,TSN300,TSNLOCV,WSHICV,WS100,WS200,WS300,BCSLSA,BCNLSA,BCSCM,BCNSCM,RAINFALL53,RAINHOUR54,RAINFALL55,RAINHOUR56,RAINFALL59,RAINHOUR60,RAINFALL61,RAINHOUR62,RAINFALL63,RAINHOUR64
count,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000,6187.000000
mean,4638.557136,2215.364959,428.364959,87.063359,17.064490,60.020527,1063.283336,348.078552,224.983999,451.353321,5.606918,55.651527,31.208502,45.319703,6.689995,501.492969,293.229352,181.654113,52.307096,84.231615,2.475998,1.102150,148.152578,627.229513,184.184742,425.046872,511.077582,96.827542,1243.512526,642.679166,789.260223,44.389526,15.290933,90.701309,256.558267,50.610312,455.246808,117.728463,168.929368,448.241312,181.236625,3.785230,1.774750,4.641708,2.174902,7.293074,3.193751,7.899193,3.277729,8.496543,3.106468
std,338.157454,2116.537299,719.958459,353.449761,161.894057,331.886825,1483.902282,646.886837,669.396054,741.934188,80.694901,286.626428,167.002856,210.400482,93.143588,856.288655,626.968187,471.807608,253.824322,330.854213,42.213905,29.269905,441.405162,1079.554211,512.409948,867.893971,944.603990,350.393680,1949.104991,951.718401,1068.789507,265.755642,131.543920,451.354639,749.427258,326.994053,1024.105237,741.270406,449.475105,1179.495061,942.142910,6.796251,2.082464,9.847186,2.834182,13.373338,3.869768,14.173389,3.933738,16.668738,3.675330
min,3834.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4651.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4766.000000,1981.000000,0.000000,0.000000,0.000000,0.000000,297.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,268.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.060000,1.000000,1.040000,1.400000,1.920000,1.500000,2.020000,1.300000,1.770000
75%,4860.000000,3560.000000,694.000000,0.000000,0.000000,0.000000,1777.500000,533.000000,0.000000,748.500000,0.000000,0.000000,0.000000,0.000000,0.000000,799.000000,271.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,981.500000,0.000000,422.000000,725.000000,0.000000,2350.000000,1110.000000,1372.500000,0.000000,0.000000,0.000000,0.000000,0.000000,130.000000,0.000000,0.000000,0.000000,0.000000,4.250000,2.830000,5.000000,3.270000,8.000000,5.330000,9.700000,4.950000,10.000000,5.000000
max,5151.000000,13785.000000,6088.000000,4891.000000,3432.000000,6346.000000,29280.000000,7052.000000,8762.000000,8533.000000,2457.000000,3859.000000,2498.000000,3251.000000,3032.000000,13708.000000,6098.000000,4424.000000,3686.000000,3867.000000,1816.000000,1294.000000,4143.000000,9536.000000,4748.000000,12677.000000,10628.000000,4379.000000,14402.000000,9883.000000,8626.000000,6932.000000,2430.000000,6007.000000,7691.000000,6722.000000,10327.000000,8752.000000,3405.000000,7476.000000,11294.000000,50.750000,12.000000,91.500000,20.650000,120.000000,23.170000,136.000000,24.000000,138.000000,24.000000

In [12]:
list(df.columns)

['DATE',
 'CV(AR)',
 'PRODUCT',
 'TON\nSTOCKPILE',
 'TON\nKROM',
 'TPSHICV',
 'TPS100',
 'TPS200',
 'TPSHICA',
 'TPS300',
 'TPS400',
 'TPSA',
 'TPS500',
 'TPS600',
 'TPSLOCV',
 'TPSLOCTS',
 'TPSLOCA',
 'PBHICV',
 'PB600',
 'PB700',
 'PBA',
 'PBTS',
 'PBLOCTS',
 'PBLOCA',
 'TSC12',
 'TSC13',
 'TSC33',
 'TSC22',
 'TSC23',
 'TSCLOCV',
 'TSCA',
 'TSN100',
 'TSN200',
 'TSN300',
 'TSNLOCV',
 'WSHICV',
 'WS100',
 'WS200',
 'WS300',
 'BCSLSA',
 'BCNLSA',
 'BCSCM',
 'BCNSCM',
 'RAINFALL53',
 'RAINHOUR54',
 'RAINFALL55',
 'RAINHOUR56',
 'RAINFALL59',
 'RAINHOUR60',
 'RAINFALL61',
 'RAINHOUR62',
 'RAINFALL63',
 'RAINHOUR64',
 'SURVEYOR',
 ' WS_TON ',
 ' CH_LITER ']

### III. Data Preprocessing

In [13]:
df.dtypes

DATE               object
CV(AR)              int64
PRODUCT            object
TON\nSTOCKPILE      int64
TON\nKROM           int64
TPSHICV             int64
TPS100              int64
TPS200              int64
TPSHICA             int64
TPS300              int64
TPS400              int64
TPSA                int64
TPS500              int64
TPS600              int64
TPSLOCV             int64
TPSLOCTS            int64
TPSLOCA             int64
PBHICV              int64
PB600               int64
PB700               int64
PBA                 int64
PBTS                int64
PBLOCTS             int64
PBLOCA              int64
TSC12               int64
TSC13               int64
TSC33               int64
TSC22               int64
TSC23               int64
TSCLOCV             int64
TSCA                int64
TSN100              int64
TSN200              int64
TSN300              int64
TSNLOCV             int64
WSHICV              int64
WS100               int64
WS200               int64
WS300               int64
BCSLSA              int64
BCNLSA              int64
BCSCM               int64
BCNSCM              int64
RAINFALL53        float64
RAINHOUR54        float64
RAINFALL55        float64
RAINHOUR56        float64
RAINFALL59        float64
RAINHOUR60        float64
RAINFALL61        float64
RAINHOUR62        float64
RAINFALL63        float64
RAINHOUR64        float64
SURVEYOR           object
 WS_TON            object
 CH_LITER          object
dtype: object

Kita dapat mengetahui kolom 'WS_TON' dan 'CH_LITER' memiliki dtypes object, dimana jika dilihat pada dataframe column tersebut seharusnya memiliki dtypes numerik (int/float). maka kolom tersebut harus di check

##### Invalid Values

In [14]:
df[' CH_LITER '].replace(' - ',np.nan,inplace=True)
df[' WS_TON '].replace(' - ',np.nan,inplace=True)

In [15]:
df[' CH_LITER '] = df[' CH_LITER '].str.replace(r'\D', '')
df[' WS_TON '] = df[' WS_TON '].str.replace(r'\D', '')

C:\Users\sonny\AppData\Local\Temp/ipykernel_7280/3282416747.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df[' CH_LITER '] = df[' CH_LITER '].str.replace(r'\D', '')
C:\Users\sonny\AppData\Local\Temp/ipykernel_7280/3282416747.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  df[' WS_TON '] = df[' WS_TON '].str.replace(r'\D', '')

In [16]:
df[' CH_LITER '] = pd.to_numeric(df[' CH_LITER '],errors='coerce')
df[' WS_TON '] = pd.to_numeric(df[' WS_TON '],errors='coerce')

##### Drop Missing Values

In [17]:
df.dropna(inplace=True)

##### Drop Date Column

In [18]:
df.drop('DATE',axis=1,inplace=True)

##### Drop Duplicated Value

In [19]:
# mencari data yang duplikat
df.duplicated().sum()

2

In [20]:
# reset index dan menghapus data duplikat
df = df.drop_duplicates(keep='first')
df.reset_index(drop = True, inplace = True)

##### Model Inference

In [21]:
# get inference set
random = 12
df_inf = df.sample(50,random_state=random)

# drop inference set from dataset
df_train_test = df.drop(df_inf.index)


# reset inference set index
df_inf.reset_index(drop=True, inplace=True)
df_inf.head(10)

,CV(AR),PRODUCT,TON\nSTOCKPILE,TON\nKROM,TPSHICV,TPS100,TPS200,TPSHICA,TPS300,TPS400,TPSA,TPS500,TPS600,TPSLOCV,TPSLOCTS,TPSLOCA,PBHICV,PB600,PB700,PBA,PBTS,PBLOCTS,PBLOCA,TSC12,TSC13,TSC33,TSC22,TSC23,TSCLOCV,TSCA,TSN100,TSN200,TSN300,TSNLOCV,WSHICV,WS100,WS200,WS300,BCSLSA,BCNLSA,BCSCM,BCNSCM,RAINFALL53,RAINHOUR54,RAINFALL55,RAINHOUR56,RAINFALL59,RAINHOUR60,RAINFALL61,RAINHOUR62,RAINFALL63,RAINHOUR64,SURVEYOR,WS_TON,CH_LITER
0,4996,E4900,1725,0,0,0,0,2624,421,278,0,0,0,0,0,0,1596,1353,0,0,0,0,0,0,1762,541,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.75,0.25,1.40,0.62,17.0,5.00,29.0,6.50,21.0,5.33,Sucofindo,95.0,397.0
1,4892,E5000,3695,1853,0,0,0,2437,709,0,0,0,0,0,0,0,0,1379,0,0,0,0,0,0,0,0,866,430,0,0,1263,964,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.00,0.5,0.72,Sucofindo,83.0,342.0
2,3912,WB,4417,400,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2221,2030,1460,0,0,0,1672,0.50,0.50,1.50,1.38,2.0,1.67,0.5,1.33,2.0,1.17,Sucofindo,73.0,313.0
3,4748,E4700,0,0,0,0,0,422,565,0,0,0,0,0,0,0,133,1360,0,0,0,0,0,0,1296,669,0,2137,0,0,2153,726,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.00,0.0,0.00,Sucofindo,111.0,358.0
4,4093,WB,4611,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1459,651,0,395,0,0,2173,0,0.25,0.25,0.38,0.50,1.5,1.92,0.0,0.00,10.0,1.58,Geoservice,45.0,184.0
5,4738,E4700,1593,0,0,0,0,0,855,0,989,0,0,136,0,0,0,690,0,0,0,0,0,0,0,0,0,0,1782,4243,0,1711,0,0,0,0,0,0,0,0,0,0,0.65,0.88,0.50,0.79,0.0,0.00,1.0,1.43,0.0,0.00,Sucofindo,103.0,446.0
6,4800,E4700,0,300,0,0,0,0,568,0,552,0,0,0,0,0,843,1254,0,0,134,0,0,0,0,0,0,3394,0,0,439,0,557,0,0,0,0,0,0,699,0,0,1.50,1.28,1.70,1.67,2.0,2.67,6.0,6.00,13.6,3.67,Sucofindo,84.0,176.0
7,4865,E4900,2501,0,0,0,0,1572,0,1112,553,0,0,0,0,0,0,0,1957,0,135,0,0,0,1614,144,0,2094,0,0,1004,1013,0,0,0,0,0,0,0,0,0,0,10.40,0.97,9.20,1.43,0.0,0.00,0.0,0.00,0.0,0.00,Sucofindo,123.0,270.0
8,4662,E4700,0,0,0,0,0,136,0,0,141,0,0,393,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7863,0,4472,0,0,0,0,0,0,0,0,0,0,0.00,0.17,0.00,0.17,0.0,0.00,0.0,0.00,0.0,0.00,Geoservice,138.0,598.0
9,3962,WB,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5059,0,0,2129,0,5.50,2.66,2.75,1.06,5.0,5.92,1.5,1.93,11.0,6.13,Geoservice,69.0,301.0

##### Splitting Dataset

In [22]:
# split data to X and y
X = df_train_test.drop(['CV(AR)'], axis=1)
y = df_train_test['CV(AR)']

In [23]:
# split X_train, X_test, y_train, y_test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=random)

# X_train shape
print('X_train shape: ', X_train.shape)

# X_test shape
print('X_test shape: ', X_test.shape)

X_train shape:  (5429, 54)
X_test shape:  (604, 54)

##### Feature Engineering (Scaling & Encoding)

In [24]:
cat = [col for col in X_train.columns if X_train[col].dtypes == 'O']
num = [col for col in X_train.columns if X_train[col].dtypes != 'O']
print('Numeric Columns:', num)
print('categorical Columns:', cat)

Numeric Columns: ['TON\nSTOCKPILE', 'TON\nKROM', 'TPSHICV', 'TPS100', 'TPS200', 'TPSHICA', 'TPS300', 'TPS400', 'TPSA', 'TPS500', 'TPS600', 'TPSLOCV', 'TPSLOCTS', 'TPSLOCA', 'PBHICV', 'PB600', 'PB700', 'PBA', 'PBTS', 'PBLOCTS', 'PBLOCA', 'TSC12', 'TSC13', 'TSC33', 'TSC22', 'TSC23', 'TSCLOCV', 'TSCA', 'TSN100', 'TSN200', 'TSN300', 'TSNLOCV', 'WSHICV', 'WS100', 'WS200', 'WS300', 'BCSLSA', 'BCNLSA', 'BCSCM', 'BCNSCM', 'RAINFALL53', 'RAINHOUR54', 'RAINFALL55', 'RAINHOUR56', 'RAINFALL59', 'RAINHOUR60', 'RAINFALL61', 'RAINHOUR62', 'RAINFALL63', 'RAINHOUR64', ' WS_TON ', ' CH_LITER ']
categorical Columns: ['PRODUCT', 'SURVEYOR']

In [25]:
numerical_pipeline = Pipeline([
('imputer', SimpleImputer(strategy='constant',fill_value=0)),
('scaler', RobustScaler())
])

categorical_ohe_pipeline = Pipeline([
('imputer', SimpleImputer(strategy='most_frequent')),
('onehot', OneHotEncoder())
])

In [26]:
pipeline_fe =  ColumnTransformer([
    ('numeric', numerical_pipeline,num),
    ('category_ohe', categorical_ohe_pipeline,cat),
])

### IV. Model Definition

##### I. Linear Regression

In [128]:
# baseline model
linreg = LinearRegression()

#pipeline model
pipe_linreg = Pipeline([
    ('pipeline_fe',pipeline_fe),
    # ('robust',RobustScaler()),
    ('linreg',linreg)
])

#Hyperparameter tuning
param_linreg = {
}

##### II. ElasticNet

In [129]:
# baseline model
enet = ElasticNet(random_state=random)

# pipeline model
pipe_enet = Pipeline([
    ('pipeline_fe',pipeline_fe),
    # ('robust',RobustScaler()),
    ('enet',enet)
])

# Hyperparameter tuning
param_enet = {
    'enet__alpha':[0.01,0.1,0.5],
    'enet__l1_ratio':[0.01,0.1,0.5,0.9,1]
}

##### III. Gradient Boost Regressor

In [130]:
# Baseline Model
gboost = GradientBoostingRegressor(loss='huber',criterion='squared_error',random_state=random)


# pipeline model
pipe_gboost = Pipeline([
    ('pipeline_fe',pipeline_fe),
    ('RobustScaler',RobustScaler()),
    ('gboost',gboost)
])

# Hyperparameter tuning
param_gboost = {
    'gboost__n_estimators':[200,250,350,400], #default 100
    'gboost__learning_rate':[0.75,0.1,1.25], #default 0.1
    'gboost__max_depth':[2], #default 3
    'gboost__min_samples_split':[5,6,7,8], #default 2
    'gboost__min_samples_leaf':[1,2,3] # default 1


}

##### IV. XGBoost Regressor

In [131]:
# Baseline Model
xgb = XGBRegressor()

# pipeline Model
pipe_xgb = Pipeline([
    ('pipeline_fe',pipeline_fe),
    # ('robust',RobustScaler()),
    ('xgb',xgb)
])

# Hyperparameter tuning
param_xgb = {
    'xgb__learning_rate':[0.01,0.05,0.1,1,1.5],
    'xgb__max_depth':[1],
    'xgb__n_estimators':[300,400,500,600]
}

##### V. Random Forest Regressor

In [132]:
# Baseline Model
rfr = RandomForestRegressor(random_state=random,n_jobs=-1)

# Pipeline Model
pipe_rfr = Pipeline([
    ('pipeline_fe',pipeline_fe),
    # ('robust',RobustScaler()),
    ('rfr',rfr)   
])

# Hyperparameter Tuning
param_rfr = {
    'rfr__n_estimators':[500,600],
    'rfr__max_depth':[6,7],
    'rfr__min_samples_split':[50]

}

### V. Model Training

##### Cross Validation each model

In [133]:
# cross validation model

model_list = [pipe_linreg,pipe_enet,pipe_gboost,pipe_xgb,pipe_rfr]

model_name_list = ['Linreg','ElasticNet','GBoost','XGB','RFR']
mean = []
std   = []
test_score = []

# for loop to get the accuracy of each model
for i in model_list:
    i.fit(X_train,y_train)
    cv = -cross_val_score(i,X_train,y_train,cv=3,scoring='neg_mean_absolute_error',verbose=1)
    mean.append(cv.mean())
    std.append(cv.std())
    i_predict = i.predict(X_test)
    test_score.append(mean_absolute_error(y_test,i_predict))


# create dataframe
cv_result = pd.DataFrame({'model':model_name_list,'Train_Mean':mean,'std':std,'Test_Score':test_score})

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.1s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.1s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    6.7s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    1.9s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    4.5s finished

In [134]:
cv_result

        model  Train_Mean       std  Test_Score
0      Linreg   39.315177  0.521648   38.284737
1  ElasticNet   72.117334  3.083334   71.796552
2      GBoost   39.753434  0.786016   38.115007
3         XGB   39.383901  0.772541   36.092043
4         RFR   39.254014  0.542702   35.873309

##### I. Linear Regression

In [135]:
# Linear Regression

model_linreg = GridSearchCV(
    pipe_linreg,
    param_linreg,
    cv=3,
    verbose=1,
    n_jobs=-1
).fit(X_train,y_train)

Fitting 3 folds for each of 1 candidates, totalling 3 fits

In [136]:
y_pred_linreg_train = model_linreg.predict(X_train)
y_pred_linreg_test = model_linreg.predict(X_test)

In [137]:
print('error train set',mean_absolute_error(y_train,y_pred_linreg_train))
print('error test set',mean_absolute_error(y_test,y_pred_linreg_test))

error train set 38.77767375459648
error test set 38.28473710553777

##### VII. ElasticNet

##### Baseline

In [138]:
model_enet = pipe_enet.fit(X_train,y_train)

In [139]:
y_pred_linreg_train = model_enet.predict(X_train)
y_pred_linreg_test = model_enet.predict(X_test)

In [140]:
print('error train set',mean_absolute_error(y_train,y_pred_linreg_train))
print('error test set',mean_absolute_error(y_test,y_pred_linreg_test))

error train set 71.31425934526692
error test set 71.79655160708592

##### Hyperparameter Tuning

In [141]:
# ElasticNet

model_enet = GridSearchCV(
    pipe_enet,
    param_enet,
    cv=5,
    verbose=1,
    n_jobs=-1
).fit(X_train,y_train)

Fitting 5 folds for each of 15 candidates, totalling 75 fits

In [142]:
model_enet.best_params_

{'enet__alpha': 0.01, 'enet__l1_ratio': 1}

In [143]:
y_pred_linreg_train = model_enet.predict(X_train)
y_pred_linreg_test = model_enet.predict(X_test)

In [144]:
print('error train set',mean_absolute_error(y_train,y_pred_linreg_train))
print('error test set',mean_absolute_error(y_test,y_pred_linreg_test))

error train set 38.774535738311336
error test set 38.29578395118188

##### III. Gradient Boosting Regressor

##### Baseline

In [145]:
model_gboost = pipe_gboost.fit(X_train,y_train)

In [146]:
y_pred_linreg_train = model_gboost.predict(X_train)
y_pred_linreg_test = model_gboost.predict(X_test)

In [147]:
print('error train set',mean_absolute_error(y_train,y_pred_linreg_train))
print('error test set',mean_absolute_error(y_test,y_pred_linreg_test))

error train set 36.326200722255486
error test set 38.11500742912326

##### Hyperparameter Tuning

In [148]:
# Gboost

model_gboost = GridSearchCV(
    pipe_gboost,
    param_gboost,
    cv=3,
    verbose=1,
    n_jobs=-1
).fit(X_train,y_train)

Fitting 3 folds for each of 18 candidates, totalling 54 fits

In [149]:
model_gboost.best_params_

{'gboost__learning_rate': 0.1,
 'gboost__max_depth': 2,
 'gboost__min_samples_leaf': 1,
 'gboost__min_samples_split': 6,
 'gboost__n_estimators': 350}

In [150]:
y_pred_linreg_train = model_gboost.predict(X_train)
y_pred_linreg_test = model_gboost.predict(X_test)

In [151]:
print('error train set',r2_score(y_train,y_pred_linreg_train))
print('error test set',r2_score(y_test,y_pred_linreg_test))

error train set 0.9822690562784622
error test set 0.9824997198589227

In [152]:
print('error train set',mean_absolute_error(y_train,y_pred_linreg_train))
print('error test set',mean_absolute_error(y_test,y_pred_linreg_test))

print('selisih',mean_absolute_error(y_train,y_pred_linreg_train)-mean_absolute_error(y_test,y_pred_linreg_test))

error train set 34.57779504253489
error test set 36.691476868274215
selisih -2.1136818257393273

##### IV. XGBoost Regressor

##### Baseline

In [153]:
model_xgb = pipe_xgb.fit(X_train,y_train)

In [154]:
y_pred_linreg_train = model_xgb.predict(X_train)
y_pred_linreg_test = model_xgb.predict(X_test)

In [155]:
print('error train set',mean_absolute_error(y_train,y_pred_linreg_train))
print('error test set',mean_absolute_error(y_test,y_pred_linreg_test))

error train set 16.493918204751104
error test set 36.09204303665666

##### Hyperparameter Tuning

In [156]:
# Gboost

model_xgb = GridSearchCV(
    pipe_xgb,
    param_xgb,
    cv=5,
    verbose=1,
    n_jobs=-1
).fit(X_train,y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

In [157]:
model_xgb.best_params_

{'xgb__learning_rate': 1, 'xgb__max_depth': 1, 'xgb__n_estimators': 600}

In [158]:
y_pred_linreg_train = model_xgb.predict(X_train)
y_pred_linreg_test = model_xgb.predict(X_test)

In [159]:
print('error train set',r2_score(y_train,y_pred_linreg_train))
print('error test set',r2_score(y_test,y_pred_linreg_test))

error train set 0.9838937153145506
error test set 0.9813595956675646

In [160]:
print('error train set',mean_absolute_error(y_train,y_pred_linreg_train))
print('error test set',mean_absolute_error(y_test,y_pred_linreg_test))

error train set 33.242329064687326
error test set 37.441058632553805

##### V. Random Forest Regressor

##### Baseline Model

In [161]:
model_rfr = pipe_rfr.fit(X_train,y_train)

In [162]:
y_pred_linreg_train = model_rfr.predict(X_train)
y_pred_linreg_test = model_rfr.predict(X_test)

In [163]:
print('error train set',mean_absolute_error(y_train,y_pred_linreg_train))
print('error test set',mean_absolute_error(y_test,y_pred_linreg_test))

error train set 14.307658139562085
error test set 35.87330936613056

##### Hyperparameter Tuning

In [164]:
# LGBM

model_rfr = GridSearchCV(
    pipe_rfr,
    param_rfr,
    cv=3,
    verbose=1,
    n_jobs=-1
).fit(X_train,y_train)

Fitting 3 folds for each of 4 candidates, totalling 12 fits

In [165]:
model_rfr.best_params_

{'rfr__max_depth': 7, 'rfr__min_samples_split': 50, 'rfr__n_estimators': 600}

In [166]:
y_pred_linreg_train = model_rfr.predict(X_train)
y_pred_linreg_test = model_rfr.predict(X_test)

In [167]:
print('error train set',mean_absolute_error(y_train,y_pred_linreg_train))
print('error test set',mean_absolute_error(y_test,y_pred_linreg_test))

error train set 37.55401446364971
error test set 39.384108692674516

### Model Inference

In [168]:
final_model = model_gboost.best_estimator_

In [169]:
final_model

Pipeline(steps=[('pipeline_fe',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(fill_value=0,
                                                                                 strategy='constant')),
                                                                  ('scaler',
                                                                   RobustScaler())]),
                                                  ['TON\nSTOCKPILE',
                                                   'TON\nKROM', 'TPSHICV',
                                                   'TPS100', 'TPS200',
                                                   'TPSHICA', 'TPS300',
                                                   'TPS400', 'TPSA', 'TPS500',
                                                   'TPS600', 'TPSLOCV',
                                                   'TPSLOCTS', 'TPSLOCA',
                                                   'PBHICV', 'PB600', 'PB700',
                                                   'PBA'...
                                                   'TSCLOCV', 'TSCA', 'TSN100',
                                                   'TSN200', ...]),
                                                 ('category_ohe',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder())]),
                                                  ['PRODUCT', 'SURVEYOR'])])),
                ('RobustScaler', RobustScaler()),
                ('gboost',
                 GradientBoostingRegressor(criterion='squared_error',
                                           loss='huber', max_depth=2,
                                           min_samples_split=6,
                                           n_estimators=350,
                                           random_state=12))])

In [5]:
# save model
import pickle

In [6]:
with open('model.pkl', 'rb') as f:
    model_inf = pickle.load(f)

In [31]:
df_inf.head(1)

,CV(AR),PRODUCT,TON\nSTOCKPILE,TON\nKROM,TPSHICV,TPS100,TPS200,TPSHICA,TPS300,TPS400,TPSA,TPS500,TPS600,TPSLOCV,TPSLOCTS,TPSLOCA,PBHICV,PB600,PB700,PBA,PBTS,PBLOCTS,PBLOCA,TSC12,TSC13,TSC33,TSC22,TSC23,TSCLOCV,TSCA,TSN100,TSN200,TSN300,TSNLOCV,WSHICV,WS100,WS200,WS300,BCSLSA,BCNLSA,BCSCM,BCNSCM,RAINFALL53,RAINHOUR54,RAINFALL55,RAINHOUR56,RAINFALL59,RAINHOUR60,RAINFALL61,RAINHOUR62,RAINFALL63,RAINHOUR64,SURVEYOR,WS_TON,CH_LITER
0,4996,E4900,1725,0,0,0,0,2624,421,278,0,0,0,0,0,0,1596,1353,0,0,0,0,0,0,1762,541,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.75,0.25,1.4,0.62,17.0,5.0,29.0,6.5,21.0,5.33,Sucofindo,95.0,397.0

In [28]:
df_inf_X = df_inf.drop(columns=['CV(AR)'],axis=1)
df_inf_y = df_inf['CV(AR)']

In [29]:
y_pred_model_inf = model_inf.predict(df_inf_X)
print('error train set',mean_absolute_error(df_inf_y,y_pred_model_inf))

error train set 37.932739435232044

In [30]:
y_pred_model_inf

array([4914.37793444, 4930.839532  , 3981.12944026, 4756.51973304,
       4063.0110475 , 4710.10806127, 4762.95426833, 4866.08501587,
       4692.31595066, 3992.87557685, 4014.58378238, 4726.53263964,
       4872.29118562, 4746.22665777, 4016.59764509, 4028.77666016,
       4723.48507044, 4816.8361045 , 4005.59015238, 4947.55025259,
       4748.66926754, 4958.81833927, 4705.56757044, 3993.45355584,
       4866.49893784, 4024.77300518, 4007.0476788 , 4031.39618077,
       4667.58640597, 4725.35316788, 4704.9135751 , 4729.35096308,
       4866.10968777, 4874.61659471, 4704.86909159, 4936.76527815,
       4694.40125797, 4741.6757575 , 4943.65431184, 4038.86600072,
       4796.07428616, 4898.43099817, 4931.12068649, 4757.88110931,
       4890.68838473, 4771.02379427, 5008.16101893, 4712.90184504,
       4062.75528686, 4734.40846885])